### PR TITLE
Added czech locale

### PR DESCRIPTION
**Pull request by knezi**

### CODE REVIEW

**Comment by tuxor1337** [comment]
Thanks for the czech translation! It would be great if you could also translate the marketplace description:

> A simple offline dictionary app in the spirit of ColorDict and GoldenDict. It scans for StarDict dictionaries stored in subdirectories of the sdcard's *dictdata* directory.
> 
> Dictionaries that you can use with FireDict can be found in many places on the web. For your convenience, I compiled a small selection of freely available dictionaries here: http://tuxor1337.github.io/firedict/dictionaries.html

> FireDict is licensed as GPL v3. See https://github.com/tuxor1337/firedict for the source code.

**Comment by tuxor1337** [comment]
By the way, are there any czech dictionaries in StarDict that you are using with this app?

**Comment by tuxor1337** [comment]
Oh, and I just noticed that you left "Lookup..." untranslated. Is that really the same in czech?

**Comment by knezi** [comment]
No problem to translate it. Where should I put the translation?
That is true, Lookup in untraslated. I was not sure how to translate it and then forget to do it. I will do it soon.
There is opensource dict for czech. Is there a list of dictionaries, so I can add it there?
I wanted to test the app in the phone, but it didn't work. I loaded it via WebIDE and there is just black screen. Do I have to do anything special? (I tried make testbuild with no result),

**Comment by tuxor1337** [comment]
At the moment, the marketplace description is not part of the source code, but I manually include it using the marketplace developer tools. Maybe you can simply put your translation just here in the comments and I will copy it over to the marketplace?

A list of dictionaries can be found here: http://tuxor1337.github.io/firedict/dictionaries.html (Link to source code: https://github.com/tuxor1337/firedict/blob/gh-pages/dictionaries.html)

For testing, just clone the repository and open the directory as packaged app in WebIDE. That should work, but icons are not displayed properly. To get the icons you have to run `make all`. The way you describe it, there seems to be a different problem with your WebIDE setup.

**Comment by knezi** [comment]
I will do it.
I still can't get it work on my GP Peak. I get the following error:
```
Error: $scope is undefined
@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/controllers.js:11:5
invoke@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:4203:14
$ControllerProvider/this.$get</</<@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:8493:11
$CompileProvider/this.$get</applyDirectivesToNode/nodeLinkFn/<@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:7739:13
forEach@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:331:11
nodeLinkFn@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:7738:11
compositeLinkFn@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:7117:13
publicLinkFn@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:6996:30
bootstrap/doBootstrap/bootstrapApply/<@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:1457:11
$RootScopeProvider/this.$get</Scope.prototype.$eval@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:14466:16
$RootScopeProvider/this.$get</Scope.prototype.$apply@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:14565:18
bootstrapApply@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:1455:9
invoke@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:4203:14
bootstrap/doBootstrap@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:1453:1
bootstrap@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:1473:1
angularInit@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:1367:5
@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:26304:5
trigger@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib/angular.min.js:2762:7
createEventHandler/eventHandler@app://e681f73a-3eab-43bf-8e83-ecaff7baebbb/js/lib
/angular.min.js:3032:9

" angular.min.js:11655
$LogProvider/this.$get</consoleLog/<() angular.min.js:11655
$ExceptionHandlerProvider/this.$get</<() angular.min.js:8596
$RootScopeProvider/this.$get</Scope.prototype.$apply() angular.min.js:14567
bootstrapApply() angular.min.js:1455
invoke() angular.min.js:4203
bootstrap/doBootstrap() angular.min.js:1453
bootstrap() angular.min.js:1473
angularInit() angular.min.js:1367
<anonymní> angular.min.js:26304
trigger() angular.min.js:2762
createEventHandler/eventHandler() angular.min.js:3032
```

and 

```"Wk: Using DictScanner in compat mode, i.e. calls are redirected to main thread." dictfactory.js:144```

I put there uncompressed Angular, so there are the real names of functions.
I have tried to observe it little bit. The problem is there is in oEvent.data (line 144 in dictfactory) just string.

**Comment by tuxor1337** [comment]
The second message is just a message for debugging. You can safely ignore it.

However, the error messages that you get from angular are mysterious. Would you please update your source code? I pushed an update to the repository yesterday.

**Comment by knezi** [comment]
I want to update my forked repository but I can't because when I try git pull firedict master I got merge conflict. Did you do anything special with my pull request?
firedict is remote - http://github.com/tuxor1337/firedict

**Comment by tuxor1337** [comment]
I just merged your pull request in the usual way using the github automerge feature. But after the merge, there were big changes to the repository. If you have new commits in your fork or changes to your working directory, there will definitely be conflicts.

Note that the locales are now located in `src/locales`

**Comment by tuxor1337** [comment]
Ooooh, I'm sorry. You are right. I made some major changes to the git history! I removed some third-party binary blobs from the git history to reduce the repository's size.

**Comment by knezi** [comment]
I did it. Still got problems with compiling...

```
mkdir -p build/thirdparty
git submodule update --init
npm install
npm WARN package.json @ No repository field.
npm WARN package.json @ No license field.
cp node_modules/angular/angular.min.js node_modules/angular-route/angular-route.min.js node_modules/angular-sanitize/angular-sanitize.min.js node_modules/angular-touch/angular-touch.min.js node_modules/es6-promise/dist/es6-promise.min.js node_modules/pako/dist/pako_inflate.min.js build/thirdparty
for src in thirdparty/dictzip.js/dictzip_sync.js thirdparty/stardict.js/stardict_sync.js thirdparty/wiki2html.js thirdparty/l10n.js; do \
        uglifyjs "$src" -cmo "build/thirdparty/$(basename ${src%.*}).min.js" ; \
done
/bin/sh: řádek 1: uglifyjs: příkaz nenalezen
/bin/sh: řádek 1: uglifyjs: příkaz nenalezen
/bin/sh: řádek 1: uglifyjs: příkaz nenalezen
/bin/sh: řádek 1: uglifyjs: příkaz nenalezen
Makefile:47: návod pro cíl „build/thirdparty/dictzip_sync.min.js“ failed
make: *** [build/thirdparty/dictzip_sync.min.js] Error 127
```

I will try to fix it later.

**Comment by tuxor1337** [comment]
This looks very much as if you are not on the latest revision of this repository. Please make sure your repository is in sync with origin master.

**Comment by knezi** [comment]
Sorry, I checkouted the wrong branch. Still with update on brach 2988d1 get the same message as I earlier (my second comment).

**Comment by tuxor1337** [comment]
It's impossible that you get the same messages since the file `controller.js` doesn't exist in the current revision of this code. But I assume that you mean you get the same messages for `app-controller.js`. Still, those error messages are mysterious and I'm not able to reproduce them in the emulator or on Firefox for Android.

In my latest commit I explicitly annotated all angular injections. Would you please try that version of the code (i.e. 606b4a1)?

**Comment by knezi** [comment]
Even the official version on marketplace does not work now (probably after update).

**Comment by tuxor1337** [comment]
As I said: Would you please check whether your issue is still present in the latest code from Github?

**Comment by knezi** [comment]
I am facing just a problem with flashing version (because I am not sure whether it is not bug in FFOS since there is unstable version). As soon as it will be fixed, I will debug Firedict. Sorry for delay.

**Comment by tuxor1337** [comment]
Okay, I found that the following page is concerned with your exact problem: http://acegautam.github.io/firefoxos/angular_issues.html This means that your issue should be solved with version 1.5.2 that I just submitted to the marketplace. Unfortunately, because of the slow review process, you might have to wait a few weeks until the new version is available officially.

**Comment by knezi** [comment]
Oh. Thanks for help a sorry for wasting your time. I have tried to flash another version and it works. I will wait.

**Comment by tuxor1337** [comment]
Oh, you are not wasting my time. In the meantime another user came up with the same issue. And by the way: the fixed version 1.5.2 is available from the Marketplace since yesterday - the reviewers seem to have a pretty quick pace at the moment :)

**Comment by knezi** [comment]
Ok. Great :+1:

**Comment by knezi** [comment]
Ok, here is the translation:
Jednoduchý slovník v duchu aplikací ColorDict a GoldenDict. Hledá slovníky formátu StarDict uložené v podsložkách složky dictdata na SD kartě.
Slovníky, které je možno použít, je možné nalézt na mnoha internetových stránkách. Pro jednoduchost větší jednoduchost jsou odkazy na některé volně dostupné slovníky na adrese http://tuxor1337.github.io/firedict/dictionaries.html
FireDict je licensován pod GPL v3. Zdrojový kód je na https://github.com/tuxor1337/firedict.

**Pull request merged**
